FROM alpine:3.20 AS static-assets

WORKDIR /assets

COPY game ./

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=static-assets /assets /usr/share/nginx/html

EXPOSE 80
