sonar.projectBaseDir=.
sonar.sources=server,game/src
sonar.tests=server/test
sonar.exclusions=server/node_modules/**,server/test/**,coverage/**,game/styles/**
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
